#### Logistic Regression
- uses sigmoid function
- 1/(1+e^-z)

In [3]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Classification/Heart_disease.csv")

In [4]:
df.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [5]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [6]:
df["Ca"].unique()

array([ 0.,  3.,  2.,  1., nan])

In [7]:
df["Thal"].unique()

array(['fixed', 'normal', 'reversable', nan], dtype=object)

In [8]:
import numpy as np
df["Thal"].replace(np.nan,'fixed',inplace=True)
df["Ca"].replace(np.nan,0.0,inplace=True)

In [9]:
df

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  0.0      normal   No  

[303 rows x 15 columns]

In [10]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [11]:
df["ChestPain"].unique()

array(['typical', 'asymptomatic', 'nonanginal', 'nontypical'],
      dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df["Thal"]=label.fit_transform(df["Thal"])
df["AHD"]=label.fit_transform(df["AHD"])
df["ChestPain"]=label.fit_transform(df["ChestPain"])

In [13]:
df.head()

Unnamed: 0  Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
0           1   63    1          3     145   233    1        2    150      0   
1           2   67    1          0     160   286    0        2    108      1   
2           3   67    1          0     120   229    0        2    129      1   
3           4   37    1          1     130   250    0        0    187      0   
4           5   41    0          2     130   204    0        2    172      0   

   Oldpeak  Slope   Ca  Thal  AHD  
0      2.3      3  0.0     0    0  
1      1.5      2  3.0     1    1  
2      2.6      2  2.0     2    1  
3      3.5      3  0.0     1    0  
4      1.4      1  0.0     1    0

In [14]:
x=df.iloc[:,1:14]

In [15]:
y=df["AHD"]

In [16]:
from sklearn.model_selection import train_test_split
x_t,x_te,y_t,y_te=train_test_split(x,y,train_size=0.8,random_state=45)

In [17]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_t,y_t)

C:\Users\prabhu\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
x_te.head()

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
104   49    1          1     120   188    0        0    139      0      2.0   
100   45    1          0     115   260    0        2    185      0      0.0   
125   45    0          2     130   234    0        2    175      0      0.6   
69    46    1          1     150   231    0        0    147      0      3.6   
83    68    1          1     180   274    1        2    150      1      1.6   

     Slope   Ca  Thal  
104      2  3.0     2  
100      1  0.0     1  
125      2  0.0     1  
69       2  0.0     1  
83       2  0.0     2

In [19]:
model.predict([[48,1,0,122,222,0,2,186,0,0.0,1,0.0,1]])

array([0])

In [20]:
y_pred=model.predict(x_te)

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score
print(accuracy_score(y_te,y_pred))

0.8688524590163934


In [22]:
print(confusion_matrix(y_te,y_pred))

[[28  4]
 [ 4 25]]


In [23]:
print(precision_score(y_te,y_pred))
print(recall_score(y_te,y_pred))

0.8620689655172413
0.8620689655172413


In [24]:
no of correct values =28+25 =53
incorrect =8

SyntaxError: invalid syntax (<ipython-input-24-5bb8cd8833ec>, line 1)

In [ ]:
                  actual
                   1    0
predicted
1                 28    4(FP)

0                 4(FN)     25


100
yes --90
no--10
imbalanced dataset

600--yes
400-no
balanced dataset