Regularization
- one of the tuning techniques
- reduce the problem of overfitting
- slightly do some modification to the learning algorithms
- model performance will be improved 
3 techniques
- Ridge(L2)
    - costfunction+lambda(slope)^2
- Lasso(L1)
    - costfunction+lambda|slope|
- Elastic
    - costfunction+lambda(slope)^2+lambda|slope|

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Regression/1000_Companies.csv")

In [2]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
df["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df["State"]=lb.fit_transform(df["State"])

In [7]:
df

R&D Spend  Administration  Marketing Spend  State        Profit
0    165349.20      136897.800      471784.1000      2  192261.83000
1    162597.70      151377.590      443898.5300      0  191792.06000
2    153441.51      101145.550      407934.5400      1  191050.39000
3    144372.41      118671.850      383199.6200      2  182901.99000
4    142107.34       91391.770      366168.4200      1  166187.94000
..         ...             ...              ...    ...           ...
995   54135.00      118451.999      173232.6695      0   95279.96251
996  134970.00      130390.080      329204.0228      0  164336.60550
997  100275.47      241926.310      227142.8200      0  413956.48000
998  128456.23      321652.140      281692.3200      0  333962.19000
999  161181.72      270939.860      295442.1700      2  476485.43000

[1000 rows x 5 columns]

In [8]:
x=df.drop("Profit",axis=1)
x

R&D Spend  Administration  Marketing Spend  State
0    165349.20      136897.800      471784.1000      2
1    162597.70      151377.590      443898.5300      0
2    153441.51      101145.550      407934.5400      1
3    144372.41      118671.850      383199.6200      2
4    142107.34       91391.770      366168.4200      1
..         ...             ...              ...    ...
995   54135.00      118451.999      173232.6695      0
996  134970.00      130390.080      329204.0228      0
997  100275.47      241926.310      227142.8200      0
998  128456.23      321652.140      281692.3200      0
999  161181.72      270939.860      295442.1700      2

[1000 rows x 4 columns]

In [9]:
y=df["Profit"]

#### Linear Regression

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=20)

In [30]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [31]:
y_pred_te=lr.predict(x_test)

In [32]:
y_pred_tr=lr.predict(x_train)

In [33]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred_te)

0.9786124893613245

In [34]:
r2_score(y_train,y_pred_tr)

0.9438445286549199

In [22]:
lr.coef_

array([ 0.55921835,  1.14731862,  0.07161405, 66.60503646])

In [57]:
## Ridge regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()
#help(ridge)

Help on Ridge in module sklearn.linear_model._ridge object:

class Ridge(sklearn.base.MultiOutputMixin, sklearn.base.RegressorMixin, _BaseRidge)
 |  Ridge(alpha=1.0, *, fit_intercept=True, normalize=False, copy_X=True, max_iter=None, tol=0.001, solver='auto', random_state=None)
 |  
 |  Linear least squares with l2 regularization.
 |  
 |  Minimizes the objective function::
 |  
 |  ||y - Xw||^2_2 + alpha * ||w||^2_2
 |  
 |  This model solves a regression model where the loss function is
 |  the linear least squares function and regularization is given by
 |  the l2-norm. Also known as Ridge Regression or Tikhonov regularization.
 |  This estimator has built-in support for multi-variate regression
 |  (i.e., when y is a 2d-array of shape (n_samples, n_targets)).
 |  
 |  Read more in the :ref:`User Guide <ridge_regression>`.
 |  
 |  Parameters
 |  ----------
 |  alpha : {float, ndarray of shape (n_targets,)}, default=1.0
 |      Regularization strength; must be a positive float. Regu

In [43]:
parameters={'alpha':[1,5,10,20,30,40,35,45,50,55,100]}
ridge_grid=GridSearchCV(ridge,parameters,cv=5)
ridge_grid.fit(x,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 5, 10, 20, 30, 40, 35, 45, 50, 55, 100]})

In [44]:
ridge_grid.best_params_

{'alpha': 100}

In [45]:
ridge=Ridge(alpha=100)

In [47]:
ridge.fit(x_train,y_train)

Ridge(alpha=100)

In [48]:
ridge.coef_

array([  0.51782827,   1.07853507,   0.09713187, -28.87193702])

#### Lasso Regression

In [50]:
from sklearn.linear_model import Lasso
lasso=Lasso()
parameters={'alpha':[1,5,10,20,30,40,35,45,50,55,100]}
lasso_grid=GridSearchCV(lasso,parameters,cv=5)
lasso_grid.fit(x,y)

C:\Users\prabhu\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 10874960739.778181, tolerance: 153098045.53727585
  model = cd_fast.enet_coordinate_descent(
C:\Users\prabhu\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 10874938232.141481, tolerance: 153098045.53727585
  model = cd_fast.enet_coordinate_descent(
C:\Users\prabhu\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 10874883430.813839, tolerance: 153098045.53727585
  model = cd_fast.enet_coordinate_descent(
C:\Users\prabhu\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: Converg

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1, 5, 10, 20, 30, 40, 35, 45, 50, 55, 100]})

In [51]:
lasso_grid.best_params_

{'alpha': 1}

In [53]:
lasso=Lasso(alpha=1)
lasso.fit(x_train,y_train)

Lasso(alpha=1)

In [54]:
lasso.coef_

array([  0.51783002,   1.07852902,   0.09713224, -32.79900828])

In [55]:
y_pred_lasso=lasso.predict(x_test)

In [56]:
r2_score(y_test,y_pred_lasso)

0.9786131310743773

In [ ]:
Task:
    - apply the boston dataset to ridge and lasso algorithms
    - find out the best alpha values using gridsearchCV
    - lasso---find the slopes values that are zero
    - find out the scores for ridge and lasso
